name: Bug Report
description: Found a bug? Help us squash it by making a bug report!
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: "Disclaimers"
      options:
        - label: "I have searched the issue tracker to check if the issue has already been reported."
          required: true
        - label: "My issue happened while using mods"
          required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us also what you expected should have happened if the game was behaving correctly.
      value: "Using the bike horn crashes the game."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: If possible, describe how the developers can get the bug to happen. It is often extremely hard to fix a bug if we don't know how to reproduce it.
      value: |
        1. Start a multiplayer campaign
        2. Spawn a bike horn with console commands
        3. Use the bike horn
        4. Observe how the game crashes
      render: bash
  - type: dropdown
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      options:
        - 1
        - <5
        - >5
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the game did the bug happen in? TODO - Explain where the version can be found.
      options:
        - 0.17.15.0
        - Other
    validations:
      required: true
  - type: input
    id: otherversion
    attributes:
      label: Other version
      description: If you selected "Other" on the version selection, please specify your selection here.
  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating system did you encounter this bug on?
      options:
        - Windows
        - MacOS
        - Linux
  - type: textarea
    id: errors
    attributes:
      label: Relevant error messages and crash reports
      description: If the game produces any text relevant to your issue, please include those in full. You can copy error messages from the in-game console by right clicking the error and selecting "copy". Crash reports will be generated in the local game files on your computer, [add proper location and other details]
      render: shell
